wobsoriano/trpc-nuxt

src/module.ts

This allows for changing nuxt `srcDir`
Solves this issue:
https://stackblitz.com/edit/nuxt-starter-uppttp?file=nuxt.config.ts

use nuxt srcDir instead of rootDir

---

src/runtime/client.ts

This method will be useful to get a key that can be used to reset the internal nuxt cache

feat: extract `getQueryKey` helper

---

src/module.ts

Method `getQueryKey` doesn't available with auto-imports

fix: auto-import `getQueryKey`

---

playground/nuxt.config.ts
src/module.ts
src/runtime/plugin.ts

Resolve #4 and #14.
Theoretically, just by setting `fetch` as `globalThis.$fetch.raw` when invoking `createTRPCClient` method will do the trick.
```ts
const client = trpc.createTRPCClient<AppRouter>({
...,
fetch: globalThis.$fetch.raw,
})
```
However, `ohmyfetch` always try to parse response body before returning `FetchResponse`, which leads to error when trpc client calls `response.json()` since response body has already been used. So we provide a _fake_ `json` method returning the parsed JSON.
```ts
fetch: (input, options) => 
globalThis.$fetch.raw(input.toString(), options).then(response => ({
...response,
json: () => Promise.resolve(response._data),
}))
```
`ohmyfetch` behaves differently with `Fetch` API when server returns an error (like HTTP 401 and 500). `Fetch` API returns the …

feat: use globalThis.$fetch to call API handler directly on server-side

---

README.md

In 0.3 default behaivior and `baseURL` value was changed

docs: Fix `baseURL` in code sample

---

src/runtime/client.ts

This resolves #9  
The main issue is that the client tries to use `serverError` from `useState` and ignores the `error` from `useAsyncData`.  
I'm not exactly sure how `serverError` is populated. I assume it has something to do with SSR. However in case without SSR the returned error is always `null`.
The proposed solution is to use the error from `useAsyncData` as initial value for `useState`.  
```ts
const serverError = useState<TError | null>(`error-${key}`, () => error.value)
```

fix: don't discard error in client

---

docs/content/1.get-started/2.usage.md

It's important to import `FetchError` from `ofetch`, not from `ohmyfetch`

docs: Add missed import in code sample

---

src/client/index.ts

This pull request fixes a bug in the `createNuxtProxyDecoration` function, which only passes the first argument to the proxied trpc client method. This causes some client methods like `subscribe` to fail because they expect more than `input` argument.

fix: pass all arguments to proxied trpc client method

---

package.json
playground/package.json
playground/pages/todo/[id].vue
pnpm-lock.yaml
src/client/links.ts

Opening this PR request to update the dependencies for support for `nuxt 3.2.2`; I was trying out `nuxt 3.2.2`, however the version of `h3` was clashing with the version used here.
These are the included changes:
- Upgrade `h3` to ensure compatibility with `nuxt 3.2.2`
- Upgrade all other dependencies (have ensured commands (dev, build) still work as expected)
- Fixed error on the id component
- Extended the `RequestInit` interface with an intersection; This is the only one I'm not 100% on; If there is a more suitable type, I'd happy update this PR.

chore: upgrade dependencies for nuxt 3.2.2

---

package.json
playground/package.json
pnpm-lock.yaml

Bumps the dependencies of `trpc-nuxt` to match the requirements for `nuxt 3.3.3` + `@nuxt/devtools 0.3.2`.
Included changes:
- Bumps dependencies
- Installed ` "@types/node": "^18.15.11"` to silence `env.process` warnings in playground

chore: bump dependencies for nuxt 3.3.3 + devtools 0.3.2

---

docs/content/1.get-started/5.tips/4.server-side-calls.md

Maybe I've got this wrong but this is what I had to do to get server side calls working. It looks like there isn't a `createCaller` function on the router from `@/server/trpc/trpc`.
Huge thanks for your work on this project @wobsoriano :1st_place_medal:

docs: Update Server Side Calls docs

---

docs/package.json
pnpm-lock.yaml

This PR fixes the broken snippets on the documentation website by upgrading the Nuxt version used for the docs to 3.7.4.
⚠️ pnpm will complain about issues with peer dependencies, but I think it won't be a problem in that case.
Fixes #125

docs: fix broken snippets

---

docs/content/1.get-started/5.tips/7.mutation.md
package.json
playground/package.json
playground/pages/index.vue
playground/server/trpc/routers/todo.ts
pnpm-lock.yaml
src/client/decorationProxy.ts
src/client/getQueryKey.ts
src/client/index.ts
src/client/types.ts

This PR improves the`getQueryKey` helper so that it's able to accept a procedure and return the cache key:
```ts
import { getQueryKey } from 'trpc-nuxt/client'
const queryKey = getQueryKey($client.getTodos, undefined)
// Access to the cached value
const { data } = useNuxtData(queryKey)
// Mutate
data.value.push({...})
// Invalidate
await refreshNuxtData(queryKey)
```
Also some cleanups

feat: getQueryKey helper

---

docs/content/1.get-started/3.client.md
playground/pages/index.vue
src/client/decorationProxy.ts
src/client/types.ts

This PR adds a `useMutation` composable kinda similar to TanStack Query [useMutation](https://trpc.io/docs/client/react/useMutation):
```vue
<script setup lang="ts">
const { $client } = useNuxtApp()
const { mutate, pending, error } = $client.login.useMutation()
const handleLogin = () => {
const name = 'John Doe';
mutate({ name });
}
</script>
<template>
<h1>Login Form</h1>
<button
:disabled="pending"
@click="handleLogin"
>
Login
</button>
<div v-if="error">
Something went wrong
</div>
</template>
```
Needs improvement but it works for now!

feat: useMutation composable

---

src/client/decorationProxy.ts
src/client/getQueryKey.ts
src/client/index.ts
src/client/links.ts
src/client/types.ts

Use the new [`@trpc/core`](https://trpc.io/docs/migrate-from-v10-to-v11#added-a-trpccore-package) package

Fix deprecated imports

---

package.json
src/client/links.ts
src/client/types.ts

This isn't a perfect fix as `@trpc/client/dist/internals/types` and `nuxt/dist/app/composables/asyncData` still can't be resolved when using `moduleResolution: "bundler"` (as they aren't publicly exported by their respective package).

fix: typings when using moduleResolution: "bundler"/"node16"

---

src/client/types.ts

Usage of internal types was a massive headache for me for last 4 hours. In some of my project typescript decides to respect "exports" field in package.json, and internal types become `any`. So data field in `useQuery()` also became `any` and i broke the prod.

Stop relying on internal types of trpc and nuxt

---

src/client/decorationProxy.ts
src/client/types.ts

This PR allows the passing of getters as inputs in queries. Closes https://github.com/wobsoriano/trpc-nuxt/issues/147.
To make a query auto-refetch on input update, you'll have to pass a `ref` or `computed`:
```ts
const id = ref(1)
$client.todo.getTodo.useQuery(id)
const anotherId = computed(() => id.value + 1)
$client.todo.getTodo.useQuery(anotherId)
```
If you have an object as input, you can do any of the ff. to re-execute a query:
1. Wrap the object in a computed property:
```ts
// This will re-execute the query if any of the following refs updates
const field = ref('someField')
const input = ref('foo')
const payload = computed(() => ({ field: field.value, value: input.value }))
$client.user.searchUser.useQuery(payload)
```
2. Convert the input to a getter and pass the refs to the …

feat: allow getter inputs

---

docs/content/1.get-started/2.usage/2.recommended.md

Since the api (`/api/[trpc].ts`) is using dynamic route parameters (https://nuxt.com/docs/guide/directory-structure/pages/), the base path for the client needs to just be `/api/` to use the correct path.

Correct plugin code in recommended docs

---

src/client/links.ts

When building to production, error.constructor.name comes from name of the class, witch gets mangled
Better to check on object itself, cause FetchError in constructor sets name.
Appreciate if you release this fix asap, bit me in production

fix: fetch error detection

---

.changeset/floppy-dingos-lose.md
src/client/links.ts
src/server/createTRPCNuxtHandler.ts

Hi Robert, thank you for this library!
We are using it extensively and had to add some logic to it, which we would like to get from upstream.
These changes allow handling events in the tRPC route using h3 directly (e.g. sendRedirect, sendStream) and reading the response on the client-side to access for example, its headers.

feat: allow advanced response handling on server & client
